package apresentacao;

import controle.TurmaControle;
import persistencia.TurmaDao;

public class TurmaAlterarFrame extends javax.swing.JFrame {

    /**
     * Creates new form AlunoAlterarFrame
     */
    public TurmaAlterarFrame() {
        initComponents();
        setDefaultCloseOperation(TurmaFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenuTurma = new javax.swing.JPanel();
        ToolBarMenuTurma = new javax.swing.JToolBar();
        ButtonAtualizarTurmaAlterar = new javax.swing.JButton();
        ButtonLimparTurmaAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelCodigoTurmaAlterar = new javax.swing.JLabel();
        LabelNomeTurmaAlterar = new javax.swing.JLabel();
        jLabelCursoTurmaAlterar = new javax.swing.JLabel();
        LabelTurmaTurnoAlterar = new javax.swing.JLabel();
        jTextNomeTurmaAlterar = new javax.swing.JTextField();
        jTextFieldCursoTurmaAlterar = new javax.swing.JTextField();
        jComboBoxTurnoTurmaAlterar = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelTurmaDisciplinaTurma = new javax.swing.JLabel();
        jTextTurmaDisciplinaTurma = new javax.swing.JTextField();
        jLabelTurmaPeriodoTurma = new javax.swing.JLabel();
        jTextTurmaPeriodoTurma = new javax.swing.JTextField();
        jComboBoxCodigo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelMenuTurma.setBackground(new java.awt.Color(204, 204, 204));

        ToolBarMenuTurma.setBackground(new java.awt.Color(204, 204, 204));
        ToolBarMenuTurma.setRollover(true);

        ButtonAtualizarTurmaAlterar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ButtonAtualizarTurmaAlterar.setText("Atualizar");
        ButtonAtualizarTurmaAlterar.setFocusable(false);
        ButtonAtualizarTurmaAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAtualizarTurmaAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAtualizarTurmaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtualizarTurmaAlterarActionPerformed(evt);
            }
        });
        ToolBarMenuTurma.add(ButtonAtualizarTurmaAlterar);

        ButtonLimparTurmaAlterar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ButtonLimparTurmaAlterar.setText("Limpar");
        ButtonLimparTurmaAlterar.setFocusable(false);
        ButtonLimparTurmaAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonLimparTurmaAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonLimparTurmaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimparTurmaAlterarActionPerformed(evt);
            }
        });
        ToolBarMenuTurma.add(ButtonLimparTurmaAlterar);

        javax.swing.GroupLayout PanelMenuTurmaLayout = new javax.swing.GroupLayout(PanelMenuTurma);
        PanelMenuTurma.setLayout(PanelMenuTurmaLayout);
        PanelMenuTurmaLayout.setHorizontalGroup(
            PanelMenuTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBarMenuTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelMenuTurmaLayout.setVerticalGroup(
            PanelMenuTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBarMenuTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atualizar Aluno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabelCodigoTurmaAlterar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCodigoTurmaAlterar.setText("Codigo Turma");

        LabelNomeTurmaAlterar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelNomeTurmaAlterar.setText("Nome");

        jLabelCursoTurmaAlterar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCursoTurmaAlterar.setText("Curso");

        LabelTurmaTurnoAlterar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelTurmaTurnoAlterar.setText("Turno");

        jTextNomeTurmaAlterar.setColumns(20);

        jTextFieldCursoTurmaAlterar.setColumns(10);

        jComboBoxTurnoTurmaAlterar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBoxTurnoTurmaAlterar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Turno", "Manhã", "Tarde", "Noite" }));
        jComboBoxTurnoTurmaAlterar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxTurnoTurmaAlterarFocusGained(evt);
            }
        });
        jComboBoxTurnoTurmaAlterar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jComboBoxTurnoTurmaAlterarComponentShown(evt);
            }
        });
        jComboBoxTurnoTurmaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTurnoTurmaAlterarActionPerformed(evt);
            }
        });

        jLabelTurmaDisciplinaTurma.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelTurmaDisciplinaTurma.setText("Disciplina");

        jTextTurmaDisciplinaTurma.setColumns(20);

        jLabelTurmaPeriodoTurma.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelTurmaPeriodoTurma.setText("Periodo");

        jTextTurmaPeriodoTurma.setColumns(2);

        jComboBoxCodigo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBoxCodigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Codigo" }));
        jComboBoxCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCodigoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCodigoTurmaAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCursoTurmaAlterar)
                                    .addComponent(LabelNomeTurmaAlterar)
                                    .addComponent(jLabelTurmaPeriodoTurma)
                                    .addComponent(jLabelTurmaDisciplinaTurma)
                                    .addComponent(LabelTurmaTurnoAlterar))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCursoTurmaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextTurmaDisciplinaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNomeTurmaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextTurmaPeriodoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTurnoTurmaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoTurmaAlterar)
                    .addComponent(jComboBoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNomeTurmaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNomeTurmaAlterar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCursoTurmaAlterar)
                    .addComponent(jTextFieldCursoTurmaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTurmaDisciplinaTurma)
                    .addComponent(jTextTurmaDisciplinaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTurmaPeriodoTurma)
                    .addComponent(jTextTurmaPeriodoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTurmaTurnoAlterar)
                    .addComponent(jComboBoxTurnoTurmaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenuTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMenuTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAtualizarTurmaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtualizarTurmaAlterarActionPerformed
        TurmaControle turmaControle = new TurmaControle();
        turmaControle.Atualizar(this);
    }//GEN-LAST:event_ButtonAtualizarTurmaAlterarActionPerformed

    private void ButtonLimparTurmaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimparTurmaAlterarActionPerformed
        TurmaControle turmaControle = new TurmaControle();
        turmaControle.limparTela(this);
    }//GEN-LAST:event_ButtonLimparTurmaAlterarActionPerformed

    private void jComboBoxTurnoTurmaAlterarComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxTurnoTurmaAlterarComponentShown

    }//GEN-LAST:event_jComboBoxTurnoTurmaAlterarComponentShown

    private void jComboBoxTurnoTurmaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTurnoTurmaAlterarActionPerformed

    }//GEN-LAST:event_jComboBoxTurnoTurmaAlterarActionPerformed

    private void jComboBoxTurnoTurmaAlterarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxTurnoTurmaAlterarFocusGained

    }//GEN-LAST:event_jComboBoxTurnoTurmaAlterarFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TurmaDao dao = new TurmaDao();
        dao.preencherComboCodigo(this);
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCodigoItemStateChanged
        TurmaDao dao = new TurmaDao();
        dao.preencherCodigoText(this);
    }//GEN-LAST:event_jComboBoxCodigoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TurmaAlterarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TurmaAlterarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TurmaAlterarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TurmaAlterarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TurmaAlterarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtualizarTurmaAlterar;
    private javax.swing.JButton ButtonLimparTurmaAlterar;
    private javax.swing.JLabel LabelNomeTurmaAlterar;
    private javax.swing.JLabel LabelTurmaTurnoAlterar;
    private javax.swing.JPanel PanelMenuTurma;
    private javax.swing.JToolBar ToolBarMenuTurma;
    private javax.swing.JComboBox jComboBoxCodigo;
    private javax.swing.JComboBox jComboBoxTurnoTurmaAlterar;
    private javax.swing.JLabel jLabelCodigoTurmaAlterar;
    private javax.swing.JLabel jLabelCursoTurmaAlterar;
    private javax.swing.JLabel jLabelTurmaDisciplinaTurma;
    private javax.swing.JLabel jLabelTurmaPeriodoTurma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCursoTurmaAlterar;
    private javax.swing.JTextField jTextNomeTurmaAlterar;
    private javax.swing.JTextField jTextTurmaDisciplinaTurma;
    private javax.swing.JTextField jTextTurmaPeriodoTurma;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jComboBoxTurnoTurmaAlterar
     */
    public javax.swing.JComboBox getjComboBoxTurnoTurmaAlterar() {
        return jComboBoxTurnoTurmaAlterar;
    }

    /**
     * @param jComboBoxTurnoTurmaAlterar the jComboBoxTurnoTurmaAlterar to set
     */
    public void setjComboBoxTurnoTurmaAlterar(javax.swing.JComboBox jComboBoxTurnoTurmaAlterar) {
        this.jComboBoxTurnoTurmaAlterar = jComboBoxTurnoTurmaAlterar;
    }

    /**
     * @return the jTextFieldCursoTurmaAlterar
     */
    public javax.swing.JTextField getjTextFieldCursoTurmaAlterar() {
        return jTextFieldCursoTurmaAlterar;
    }

    /**
     * @param jTextFieldCursoTurmaAlterar the jTextFieldCursoTurmaAlterar to set
     */
    public void setjTextFieldCursoTurmaAlterar(javax.swing.JTextField jTextFieldCursoTurmaAlterar) {
        this.jTextFieldCursoTurmaAlterar = jTextFieldCursoTurmaAlterar;
    }

    /**
     * @return the jTextNomeTurmaAlterar
     */
    public javax.swing.JTextField getjTextNomeTurmaAlterar() {
        return jTextNomeTurmaAlterar;
    }

    /**
     * @param jTextNomeTurmaAlterar the jTextNomeTurmaAlterar to set
     */
    public void setjTextNomeTurmaAlterar(javax.swing.JTextField jTextNomeTurmaAlterar) {
        this.jTextNomeTurmaAlterar = jTextNomeTurmaAlterar;
    }

    /**
     * @return the jTextTurmaDisciplinaTurma
     */
    public javax.swing.JTextField getjTextTurmaDisciplinaTurma() {
        return jTextTurmaDisciplinaTurma;
    }

    /**
     * @param jTextTurmaDisciplinaTurma the jTextTurmaDisciplinaTurma to set
     */
    public void setjTextTurmaDisciplinaTurma(javax.swing.JTextField jTextTurmaDisciplinaTurma) {
        this.jTextTurmaDisciplinaTurma = jTextTurmaDisciplinaTurma;
    }

    /**
     * @return the jTextTurmaPeriodoTurma
     */
    public javax.swing.JTextField getjTextTurmaPeriodoTurma() {
        return jTextTurmaPeriodoTurma;
    }

    /**
     * @param jTextTurmaPeriodoTurma the jTextTurmaPeriodoTurma to set
     */
    public void setjTextTurmaPeriodoTurma(javax.swing.JTextField jTextTurmaPeriodoTurma) {
        this.jTextTurmaPeriodoTurma = jTextTurmaPeriodoTurma;
    }

    /**
     * @return the jComboBoxCodigo
     */
    public javax.swing.JComboBox getjComboBoxCodigo() {
        return jComboBoxCodigo;
    }

    /**
     * @param jComboBoxCodigo the jComboBoxCodigo to set
     */
    public void setjComboBoxCodigo(javax.swing.JComboBox jComboBoxCodigo) {
        this.jComboBoxCodigo = jComboBoxCodigo;
    }

 
}
